name: CI pipeline
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout latest code"
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y jq
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12
      - name: Run unit tests
        run: |
          npm test
      - name: "Bump version"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Reac latest version"
        run: |
          VERSION=`cat package.json | jq -r .version`
          echo "$VERSION"
